# NumPy: Numerical Python Basics

When working with Data Science, Machine Learning, or AI, Python's standard lists are simply too slow and memory-intensive. To process millions of data points efficiently, we use **NumPy** (Numerical Python).

---

## 1. What is NumPy?
NumPy is the fundamental package for scientific computing in Python.
- **The ndarray**: The core of NumPy is the **N-dimensional array** (an object that stores items of the same type in a contiguous block of memory).
- **Speed**: NumPy arrays are written in C, making mathematical operations up to **100x faster** than standard Python lists.
- **Vectorization**: Instead of writing `for` loops to perform operations on every item, you can perform math on the entire array at once!

---

## 2. Standard Lists vs. NumPy Arrays
| Feature | Python List | NumPy Array |
| :--- | :--- | :--- |
| **Data Types** | Can hold mixed types (strings, ints, dicts) | Must hold homogeneous types (e.g., all float64) |
| **Memory** | Highly fragmented (stores pointers to objects) | Highly compact (stores contiguous raw values) |
| **Operations** | Element-wise math requires explicit loops | Element-wise math is native (`arr * 2`) |
| **Dimensionality**| Nested lists | Native support for 1D, 2D (matrices), and N-D grids |

---

## 3. Basic Operations

### Array Creation



In [ ]:
import numpy as np

# From a list
arr = np.array([1, 2, 3, 4])

# Helper functions
zeros = np.zeros((3, 3))       # 3x3 matrix of zeros
ones = np.ones((2, 5))         # 2x5 matrix of ones
arange = np.arange(0, 10, 2)   # Array of [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)# 5 evenly spaced numbers: [0., 0.25, 0.5, 0.75, 1.]




### Array Indexing & Slicing
Slicing in NumPy is extremely powerful.



In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])   # Row 0, Col 1 -> 2
print(arr[:, 1])   # All rows, Col 1 -> [2, 5]


2
[2 5]




### Broadcasting and Element-wise Math



In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)  # [11, 22, 33] (Element-wise addition)
print(a * 2)  # [2, 4, 6]    (Broadcasting scalar multiplication)


[11 22 33]
[2 4 6]




---

## 4. Fundamental Functions and Aggregations
- **`arr.shape`**: Returns a tuple showing the dimensions (e.g., `(3, 4)` for 3 rows, 4 columns).
- **`arr.reshape(rows, cols)`**: Changes the shape without modifying the data.
- **`arr.mean()`**: Computes the average value.
- **`arr.sum()`**: Sums all elements.
- **`arr.std()`**: Computes the standard deviation.

---

## 5. Best Practices
1. **Never loop over NumPy arrays**: If you write `for item in arr:`, you lose all the C-speed benefits of NumPy. Use vectorized expressions.
2. **Specify dtypes**: If you know your data is only small integers, specifying `dtype=np.int8` saves massive amounts of RAM.
3. **Avoid Copies (Be careful with Slices)**: Slicing an array creates a **view**, not a copy. If you modify a slice, the original array changes too! Use `.copy()` if you need an isolated copy.

## Resources

- **Official NumPy Documentation** – https://numpy.org/doc/stable/
- **NumPy Quickstart Tutorial** – https://numpy.org/doc/stable/user/quickstart.html
- **Real Python: NumPy Tutorial** – https://realpython.com/numpy-tutorial/
- **Stanford CS231n: Python NumPy Tutorial** – https://cs231n.github.io/python-numpy-tutorial/
- **From Python to NumPy (Book)** – https://www.labri.fr/perso/nrougier/from-python-to-numpy/
- **NumPy Illustrated (Visual Guide)** – https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d



# Examples & Demonstrations
Below are runnable examples demonstrating the concepts covered in this module.


In [ ]:
# Examples: Harnessing the Power of Vectorized Calculations

import numpy as np

# --- 1. Vectorized Speed Comparison ---


In [ ]:
def speed_demo():
    print("--- Speed: Python List vs. NumPy Array ---")
    size = 1_000_000
    
    # Standard Python list approach
    python_list = list(range(size))
    # We want to add 2 to every item. In standard Python, we must loop:
    import time
    start = time.perf_counter()
    python_list_result = [x + 2 for x in python_list]
    end = time.perf_counter()
    list_duration = end - start
    print(f"Python List comprehension: {list_duration:.5f} seconds")
    
    # NumPy array approach
    numpy_array = np.arange(size)
    # We do the exact same addition using native vectorization!
    start = time.perf_counter()
    numpy_array_result = numpy_array + 2
    end = time.perf_counter()
    array_duration = end - start
    print(f"NumPy Vectorized addition: {array_duration:.5f} seconds")
    print(f"NumPy is ~{list_duration / array_duration:.1f}x faster!\n")

# --- 2. Multi-Dimensional Array (Matrices) ---


In [ ]:
def matrix_demo():
    print("--- Matrix Manipulations ---")
    # Create a 2D array (3 rows, 4 columns)
    matrix = np.array([
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ])
    
    print("Original Matrix:")
    print(matrix)
    print(f"Shape: {matrix.shape}")  # (3, 4)
    print(f"Number of dimensions: {matrix.ndim}")  # 2
    
    # Indexing and slicing: [row_slice, col_slice]
    print("\nRow 1 (second row):", matrix[1])  # [5, 6, 7, 8]
    print("Column 2 (third column):", matrix[:, 2])  # [3, 7, 11]
    print("Sub-matrix (top-left 2x2):\n", matrix[0:2, 0:2]) # [[1 2] [5 6]]
    
    # Reshaping: Transform to 2 rows, 6 columns
    reshaped = matrix.reshape(2, 6)
    print("\nReshaped Matrix (2x6):\n", reshaped)

# --- 3. Boolean Masking (Filtering) ---


In [ ]:
def filtering_demo():
    print("\n--- Boolean Masking (Smart Filtering) ---")
    grades = np.array([85, 42, 90, 78, 61, 55, 95])
    
    # Create a condition mask
    passed_mask = grades >= 60
    print("Condition Mask (grades >= 60):", passed_mask)
    
    # Apply the mask to retrieve values
    passing_grades = grades[passed_mask]
    print("Filtered Passing Grades:", passing_grades)
    
    # Modify values matching a condition (e.g., curved grade for failing students)
    grades[grades < 60] += 5
    print("Curved Grades:", grades)


In [ ]:
speed_demo()
matrix_demo()
filtering_demo()


--- Speed: Python List vs. NumPy Array ---
Python List comprehension: 0.09916 seconds
NumPy Vectorized addition: 0.00320 seconds
NumPy is ~31.0x faster!

--- Matrix Manipulations ---
Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Number of dimensions: 2

Row 1 (second row): [5 6 7 8]
Column 2 (third column): [ 3  7 11]
Sub-matrix (top-left 2x2):
 [[1 2]
 [5 6]]

Reshaped Matrix (2x6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

--- Boolean Masking (Smart Filtering) ---
Condition Mask (grades >= 60): [ True False  True  True  True False  True]
Filtered Passing Grades: [85 90 78 61 95]
Curved Grades: [85 47 90 78 61 60 95]


# Practice Exercises
EXERCISES: The Array Wizard

EXERCISE 1: The Matrix Builder
1. Create a 1D NumPy array containing numbers from 10 to 19 (inclusive).
2. Reshape this array into a 2D matrix of shape (2, 5).
3. Print the shape, the number of dimensions, and the matrix itself.

EXERCISE 2: Statistical Aggregations
1. Create a 1D array of 20 random integers between 1 and 100.
   (Hint: use np.random.randint(1, 101, 20))
2. Calculate and print:
   - The maximum value.
   - The minimum value.
   - The mean (average).
   - The index of the maximum value (Hint: np.argmax()).

EXERCISE 3: Temperature Converter
1. Create an array of daily high temperatures in Fahrenheit:
   temps_f = [72.5, 68.0, 81.2, 90.5, 78.8, 65.3, 70.0]
2. Convert this list to a NumPy array.
3. Convert all temperatures to Celsius using the formula: C = (F - 32) * 5/9.
   (Do this in a single vectorized step!)
4. Print the resulting Celsius array rounded to 1 decimal place (Hint: np.round()).

In [ ]:
import numpy as np

# TODO: Implement the exercises above


In [ ]:
def exercise1():
    arr = np.arange(10, 20)
    arr = arr.reshape(2, 5)
    print(arr.shape)
    print(arr.ndim)
    print(arr)


In [ ]:
def exercise2():
    arr = np.random.randint(1, 101, 20)
    print(arr)
    print(arr.max())
    print(arr.min())
    print(arr.mean())
    print(np.where(arr == arr.max()))
    print(arr.argmax())


In [ ]:
def exercise3():
    temps_f = [72.5, 68.0, 81.2, 90.5, 78.8, 65.3, 70.0]
    arr = np.array(temps_f)
    arr = (arr - 32) * 5/9
    print(arr)
    print(np.round(arr, 1))

if __name__ == "__main__":
    exercise1()
    print("\n")
    exercise2()
    print("\n")
    exercise3()


(2, 5)
2
[[10 11 12 13 14]
 [15 16 17 18 19]]


[24 19 67 81 27 88 97 92 26 12 55 71 66 85 70 76 30 45 89 94]
97
12
60.7
(array([6]),)
6


[22.5        20.         27.33333333 32.5        26.         18.5
 21.11111111]
[22.5 20.  27.3 32.5 26.  18.5 21.1]
